#######项目名称#######
projectName: koa-shop-api
#######备注
remark: null
#######正式/测试 production or develop
env: production
#######Node启动端口
nodeport: 3001
#######WebSocket端口
soketport: 3002
########web端口
webport: 3000

#######最后一次上线日期 yyyy/MM/dd
#lastDeployDate:

#######Session Key
session_key: session_id
#######Session Secret
sessionSecret: secretCat
#######Session Timeout
sessionTimeout: 30 * 60 * 1000

#######OSS配置 Start
#OSS Key
#OSS Secret
#######OSS配置 End
#########Momgo配置 Start
#DB config
DB:
  host: 'localhost' # 这也是注释，不会输出的
  port: 3306
  database: 'project_progress'
  user: 'root'
  password: '123456'
#正式mongo地址
#DB_CONN_STR: 'mongodb://localhost:27017/BookPlatform'
#########Momgo配置 End
#######Redis配置 Start
#redis_cluster:
#   [{
#     host: '172.16.100.101',
#     port: '16100'
#   },{
#     host: '172.16.100.102',
#     port: '16100'
#   },{
#     host: '172.16.100.103',
#     port: '16100'
#   }]
#######Redis配置 End

#######后端参数 Start
#后端Rest链接地址 以HTTP开头

#######后端参数 End

#demokey:1

###地址的配置
#serverPath: "http://172.16.100.116:30062/"

#######请求参数配置
safe_path: "urlPath"
safe_body: "urlBody"
#######请求白名单（配置的URL不进行加密和解密）支持*，如：/ABCD/*
safe_filter_url: ['/login', '/reg']
#######安全模块配置 End